FROM golang
RUN mkdir oreclient_install_dir
RUN apt-get update
RUN apt-get install libaio1 libaio-dev
RUN apt-get install unzip -y

WORKDIR /oreclient_install_dir/
RUN curl -o instantclient-basic-linux.x64-12.2.0.1.0.zip http://plinrepo1v.standardbank.co.za/repo/software/oracle/instant-client-12/instantclient-basic-linux.x64-12.2.0.1.0.zip
RUN curl -o instantclient-sdk-linux.x64-12.2.0.1.0.zip http://plinrepo1v.standardbank.co.za/repo/software/oracle/instant-client-12/instantclient-sdk-linux.x64-12.2.0.1.0.zip

RUN cd /oreclient_install_dir ; unzip /oreclient_install_dir/instantclient-basic-linux.x64-12.2.0.1.0.zip
RUN cd /oreclient_install_dir ; unzip /oreclient_install_dir/instantclient-sdk-linux.x64-12.2.0.1.0.zip

ENV PKG_CONFIG_PATH "/oreclient_install_dir/instantclient_12_2"
ENV LD_LIBRARY_PATH "/oreclient_install_dir/instantclient_12_2"

RUN ln -s /oreclient_install_dir/instantclient_12_2/libclntsh.so.12.1 /usr/lib/libclntsh.dylib
RUN ln -s /oreclient_install_dir/instantclient_12_2/libclntsh.so.12.1 /usr/lib/libclntsh.so
RUN ln -s /oreclient_install_dir/instantclient_12_2/libocci.so.12.1 /usr/lib/libocci.dylib
RUN ln -s /oreclient_install_dir/instantclient_12_2/libocci.so.12.1 /usr/lib/libocci.so
